name: Upload a file

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore: main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image metadata
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            python
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            # type=sha,format=short,prefix=
            # pull request event
            type=ref,event=pr,format=short,prefix=pr-
            # type=ref,event=branch

      - name: Echo image labels 
        shell: bash
        run: |
          echo "Image name: ${{ steps.image-meta.outputs.tags }}"
          echo "Image digest: ${{ steps.image-meta.outputs.digest }}"
          echo "Image tags: ${{ steps.image-meta.outputs.tags }}"
          echo "Image labels: ${{ steps.image-meta.outputs.labels }}"

      
