name: Upload a file

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore: main
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - name: Upload Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

      
