name: Check availability of file

on:
  push:
    branches: main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  check_file:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./downloaded-artifact
      - name: Show artifact
        run: |
          ls -alR ./downloaded-artifact
          if [ -f ./downloaded-artifact/world.txt ]; then
            echo "File is available."
          else
            echo "File is not available."
            exit 1
          fi
          
      - name: Image metadata
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            python
          tags: |
            type=sha

      - name: Echo image labels 
        shell: bash
        run: |
          echo "Image name: ${{ steps.image-meta.outputs.tags }}"
          echo "Image digest: ${{ steps.image-meta.outputs.digest }}"
          echo "Image tags: ${{ steps.image-meta.outputs.tags }}"
          echo "Image labels: ${{ steps.image-meta.outputs.labels }}"
        
      
  
