name: Check availability of file

on:
  pull_request:
    branches:
      - main

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - shell: bash
        run: ls -R
        
      
  
