name: Sane release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  check_file:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./downloaded-artifact

      - name: Show artifact
        run: |
          ls -alR ./downloaded-artifact

      - name: Image metadata
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            python
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=semver,pattern={{raw}}

      - name: Echo image labels 
        shell: bash
        run: |
          echo "Image name: ${{ steps.image-meta.outputs.tags }}"
          echo "Image digest: ${{ steps.image-meta.outputs.digest }}"
          echo "Image tags: ${{ steps.image-meta.outputs.tags }}"
          echo "Image labels: ${{ steps.image-meta.outputs.labels }}"

